# Generated by Django 4.2.3 on 2023-07-30 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='date',
            field=models.DateField(default='2023-07-30', null=True),
        ),
    ]
