# Generated by Django 4.2.3 on 2023-07-31 05:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_invoicedetail_options_alter_invoice_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invoicedetail',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='invoicedetail',
            unique_together=set(),
        ),
    ]
